### ISSUE TITLE
easy installation guidance

### ISSUE THREAD

**Issue by FathiMahdi** [AmmarCodes/obsidian-quran-vault#3]
Hi, first thanks for the great effort, I have a problem dealing with ```yarn```
can you provide more details about the installation? 

error
```shel
00h00m00s 0/0: : ERROR: There are no scenarios; must have at least one.l
```

**Comment by AmmarCodes** [comment]
Hi @FathiMahdi 👋 

The project is using v1, I just gave it another try using version `1.22.19` and it compiled without problems.

This is the installation docs for Yarn v1: https://classic.yarnpkg.com/en/docs/install/

Which `yarn` version are you using? could you share more details/logs?
