### ISSUE TITLE
Translated Quran in Obsidian

### ISSUE THREAD

**Issue by iamverified** [AmmarCodes/obsidian-quran-vault#4]
Hi

I was wondering if there is a way to create an obsidian vault with quran in English translation using the same scripts? I can see that the  English version is available in JSON at https://github.com/risan/quran-json.git.

**Comment by AmmarCodes** [comment]
Hi @iamverified,

The English version is ready https://github.com/AmmarCodes/obsidian-quran-vault/releases/tag/v1.0
