### ISSUE TITLE
RTL bug

### ISSUE THREAD

**Issue by ghost** [AmmarCodes/obsidian-quran-vault#6]
I have a problem, which is that the serial numbers go out of their normal places, as well as the symbols for making notes.
I enabled writing from right to left, but the problem was not solved
Does anyone know the name of this problem so I can search for it online?

![image](https://github.com/AmmarCodes/obsidian-quran-vault/assets/113709974/82c5fca7-2e8a-4a3f-9448-b22a5daa363c)

**Comment by AmmarCodes** [comment]
That seems unrelated to the project itself, in the new Obsidian 1.6 there was an improvement on RTL but still has issues like you mentioned. I'd wait for Obsidian to fix that.
