### ISSUE TITLE
[Feature Request] Efficient Template: Instead of Individual files for each Ayah, Put the Ayat Surah wise ... (and other stuff in description)

### ISSUE THREAD

**Issue by AfzGit** [AmmarCodes/obsidian-quran-vault#7]
As-Salam Walaikum. Instead of having each Ayah in a seperate file, it will be better if it is grouped Surah wise. 

These are some cons to the current approach:
- Obsidian starts lagging if there are too many similar notes (like `"1.md" * 114`)
- does not take into account different names of the Same Surahs (like "Iklas" and "Ahad")
- both files and tags take some processing power and lag the whole vault up a bit.
- refering to the previous and next Ayah takes longer
- searching by surah number is missing

i would like to present the following solution to this problem:

![image](https://github.com/AmmarCodes/obsidian-quran-vault/assets/63847494/fd1a6361-6a7a-4c9a-a4d2-6958b225d155)

- we can search the Surah by number
- we can view prev and next Ayahs easily
- we can embed easier: 

![image](https://github.com/AmmarCodes/obsidian-quran-vault/assets/63847494/a1acba14-c47c-4295-baa5-1a5a584046ca)

- Alias support can also be added to support different names for the same Surah

![image](https://github.com/AmmarCodes/obsidian-quran-vault/assets/63847494/12d69546-6338-41b3-af5c-3bed82a2cc4e)

Let me know what you think about it. BarakAllahu Feek.

**Comment by AmmarCodes** [comment]
Waalaykom assalam 👋 

Great suggestion! 

With that implemented one could even put the whole folder inside their vault instead of having a separate vault (with the current implementation separate vault makes sense given the amount of files).

I'll work on that soon inshaAlla.

JazakaAllah khaira 👍

**Comment by AfzGit** [comment]
InshaAllah. Ameen wa iyyak. May Allah make it easy and accept it from you.

**Comment by AmmarCodes** [comment]
@AfzGit I'm testing this out with footnotes instead of heading, it seems cleaner when embedded. Also the auto complete will work as expected when starting to type `![[^`

Here's a comparision:

| footnote | heading |
| ------ | ------ |
| ![image](https://github.com/AmmarCodes/obsidian-quran-vault/assets/351256/9ebecdaf-df5c-430c-bf1c-31f9a791933c) | ![image](https://github.com/AmmarCodes/obsidian-quran-vault/assets/351256/799dae85-5213-43a2-95bc-ca4c38e9b51a) |

Which one you think is better?

**Comment by AfzGit** [comment]
Using headers would be better:

- Using headers is essential as translations, transliterations and custom notes can be later added more easily. 
- Currently footnotes break upon using new lines. 
- The formatting of footnotes is also very strict, you will need to stick to the specified format by obsidian or else it will not work
- Managing a long list of footnotes is also harder than using heading.
- header generally provide more flexibility and are also well understood by others
- Plus, there is a way to get cleaner embeds below: 

Clean Embeds
---

You can get embed without the heading using this snippet:

no-embed-header.css
```css
.no-head .markdown-embed h1,
.no-head .markdown-embed h2,
.no-head .markdown-embed h3,
.no-head .markdown-embed h4,
.no-head .markdown-embed h5,
.no-head .markdown-embed h6 {
    display: none;
}
```

Place the above in your obsidian `snippets` folder, enable it in `Appearance` setting, then add this to each Surah's Yaml Header

```yaml
---
cssclasses:
  - no-head
---
```


- Before: ![image](https://github.com/AmmarCodes/obsidian-quran-vault/assets/63847494/89ce535b-8d52-4015-b417-3e5f24337b0a) 

- After: ![image](https://github.com/AmmarCodes/obsidian-quran-vault/assets/63847494/c1c601df-dfbd-476f-aacd-6f3c088026fe) 

A big pro to this approach would be that the one who wants header can have them by not including the no-head in cssclasses of their surah's

if you want to apply it on the whole vault without using the cssclasses yaml header you could also instead use this snippet:

no-embed-header-all.css
```css
.markdown-embed h1,
.markdown-embed h2,
.markdown-embed h3,
.markdown-embed h4,
.markdown-embed h5,
.markdown-embed h6 {
    display: none;
}
```

**Comment by AmmarCodes** [comment]
Would you be able to test this vault and give me your feedback?

We need to add extra instruction how to properly embed an Ayah once we're done, but for now you know how it do it 😄 

[Quran.zip](https://github.com/user-attachments/files/15836360/Quran.zip)

**Comment by AfzGit** [comment]
Looks good! Although not numbering the Surah makes file navigation confusing. I would suggest numbering the Surah filenames which has the added benefit of searching via surah number. 

Pros:
- The different ways to pronounce the surah make it so that using `[[` is not reliable enough. Adding surah number adds a layer of reliability.
- Looks well organized in the file explorer of obsidian
- Faster searching

Sample:
![image](https://github.com/AmmarCodes/obsidian-quran-vault/assets/63847494/1fd1ab26-4eec-4213-920b-41172347aa99)

**Comment by AmmarCodes** [comment]
@AfzGit JazakaAllah khaira!

Would you check it now?
[Quran.zip](https://github.com/user-attachments/files/15837655/Quran.zip)

**Comment by AfzGit** [comment]
@AmmarCodes Looks almost perfect. Aliases still serve no purpose. Here are aliases that have some purpose

![image](https://github.com/AmmarCodes/obsidian-quran-vault/assets/63847494/eb97fd10-9a31-4a19-a503-8eeee0793d9e)

This is an example where i:
1. Used the English name of the Surah
2. Wrote the surah name pronounced in a different way
3. wrote surah number + arabic name
4. wrote surah number in arabic + arabic name

this is just an example. It does not have to exactly be like this. Maybe you can fetch aliases from [Here](https://tanzil.net/docs/quran_metadata):
- [XML](https://tanzil.net/res/text/metadata/quran-data.xml)
- [JS](https://tanzil.net/res/text/metadata/quran-data.js)

![image](https://github.com/AmmarCodes/obsidian-quran-vault/assets/63847494/231d3fd1-5412-4282-86b9-85319ab19072)

using the above data you can also add ayah YAML header

![image](https://github.com/AmmarCodes/obsidian-quran-vault/assets/63847494/6551e0e8-df69-4679-8395-c0406406922f)

**Comment by AmmarCodes** [comment]
I just released the new version https://github.com/AmmarCodes/obsidian-quran-vault/releases/tag/v2.0, thanks a lot for the suggestion and for testing it.
