### ISSUE TITLE
[Feature Request] create a plugin for Quran

### ISSUE THREAD

**Issue by AmmarCodes** [AmmarCodes/obsidian-quran-vault#8]
## For a first iteration

Create a plugin that shows a modal then inserts an Ayah.

- Modal shows 2 drop downs, one for Surah and one for Ayah
- User selects Surah and Ayah and click insert
- The plugin would insert the selected Ayah in a callout

## Features for future iterations

- Add a custom callout for Ayah
- Add more options to the modal
  - Select language
  - Select more than one consequetive Ayahs

**Comment by AfzGit** [comment]
I hope you make one. Currently i use this one for Ayah Retrival: [Quran Lookup](https://github.com/abuibrahim2/quranlookup). But it has not been updated in over 2 years, there are some translation errors, and having no model makes retriving harder.

Nevertheless, if you decide to make one, this Quran Lookup plugin may be useful as a reference.

**Comment by O1Anas** [comment]
assalamo 3alaykom Ammar, thank you so much for that beautiful quran helper plugin, may allah grant us the heights of heaven ❤️

**Comment by AmmarCodes** [comment]
@AnasImr Wa alakom assalam, thank you for your kind words!

Alhamdulillah the plugin is ready at: https://github.com/ammarcodes/obsidian-quran-helper-plugin
